def hamiltonian_on_site():
    pass



def hamiltonian_list_names(
    all_terms, on_site, on_bond, special_on_site, special_on_bond, subhamiltonian
):
    ham_expr = []
    hamiltonian_list_names(subhamiltonian)


def model_info():
    hamiltonian = {
        # ### SKELETON
        "skeleton_model_name": {
            "nb_param": "list_param",
            "spin_qn_name_default": "qn_model_alone",
            "spin_qn_name_allowed": "qname_allowed",
            "period": "ham_periodicity",
            "submodel": "list_of_submodel",
            "ham_expr": "expression_to_add__1-ONSITE__2-NEAREST_NEIGHBOR__3-SPECIAL-SITE__4-SPECIAL-BOND",
        },
        # ### sh-so CHAINS
        "hx": {
            "nb_param": 1,
            "qname_ideal": ["None", (1,)],
            "qname_allowed": ["None"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[(("M", -1.0, 0), ("Sx", 0))], [], [], []],
        },
        "hz": {
            "nb_param": 1,
            "qname_ideal": ["U1", (1,)],
            "qname_allowed": ["None", "U1"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[(("M", -1.0, 0), ("Sz", 0))], [], [], []],
        },
        # 'hzR' : {'nb_param' : 1, 'qname_ideal' : ['U1', (1,)],'qname_allowed' : ['None','U1'], 'period' : -1,
        #     'submodel' : [],
        #     'ham_expr' : [ [( 0, ('MR', [-1.] ), ('Sz', 0))], [], [], [] ] },
        "xy": {
            "nb_param": 1,
            "qname_ideal": ["SU2", (2,)],
            "qname_allowed": ["None", "U1", "SU2"],
            "period": 1,
            "submodel": [],
            "ham_expr": [
                [],
                [
                    (("M", 1.0 / 2.0, 0), ("SpoSm", 0)),
                    (("M", 1.0 / 2.0, 0), ("SmoSp", 0)),
                ],
                [],
                [],
            ],
        },
        # 'xy-2site' : {'nb_param' : 1, 'qname_ideal' : ['SU2', (2,)],'qname_allowed' : ['None','U1','SU2'], 'period' : 2,
        #     'submodel' : [],
        #     'ham_expr' : [ [], [], [( 0, ('M', [1./2.]), ('SpoSm', 0)),(0, ('M', 1./2.),('SmoSp', 0))], []] },
        "xydimer": {
            "nb_param": 2,
            "qname_ideal": ["SU2", (2,)],
            "qname_allowed": ["None", "U1", "SU2"],
            "period": 2,
            "submodel": [],
            "ham_expr": [
                [],
                [
                    (("M", 1.0 / 2.0, 0), ("SpoSm", 0)),
                    (("M", 1.0 / 2.0, 0), ("SmoSp", 0)),
                    (("M", 1.0 / 2.0, 1), ("SpoSm", 1)),
                    (("M", 1.0 / 2.0, 1), ("SmoSp", 1)),
                ],
                [],
                [],
            ],
        },
        "xyflux": {
            "nb_param": 1,
            "qname_ideal": ["SU2", (2,)],
            "qname_allowed": ["None", "U1", "SU2"],
            "period": 1,
            "submodel": [],
            "ham_expr": [
                [],
                [
                    (("EXP", [1.0 / 2.0, +1.0j], [0, 1]), ("SpoSm", 0)),
                    (("EXP", [1.0 / 2.0, -1.0j], [0, 1]), ("SmoSp", 0)),
                ],
                [],
                [],
            ],
        },
        "zz": {
            "nb_param": 1,
            "qname_ideal": ["SU2", (2,)],
            "qname_allowed": ["None", "U1", "SU2"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[], [(("M", 1.0, 0), ("SzoSz", 0))], [], []],
        },
        "zz2sites": {
            "nb_param": 1,
            "qname_ideal": ["SU2", (2,)],
            "qname_allowed": ["None", "U1", "SU2"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[], [(("M", 1.0, 0), ("SzoSz", 0))], [], []],
        },
        "zzdimer": {
            "nb_param": 2,
            "qname_ideal": ["SU2", (2,)],
            "qname_allowed": ["None", "U1", "SU2"],
            "period": 2,
            "submodel": [],
            "ham_expr": [
                [],
                [(("M", 1.0, 0), ("SzoSz", 0)), (("M", 1.0, 1), ("SzoSz", 1))],
                [],
                [],
            ],
        },
        "SxLEFT": {
            "nb_param": 1,
            "qname_ideal": ["SU2", (2,)],
            "qname_allowed": ["None", "U1", "SU2"],
            "period": -1,
            "submodel": [],
            "ham_expr": [
                [],
                [],
                [
                    (("M", 1.0, 0), ("Sp", ("LEFT", 0))),
                    (("M", 1.0, 0), ("Sm", ("LEFT", 0))),
                ],
                [],
            ],
        },
        "SxRIGHT": {
            "nb_param": 1,
            "qname_ideal": ["SU2", (2,)],
            "qname_allowed": ["None", "U1", "SU2"],
            "period": -1,
            "submodel": [],
            "ham_expr": [
                [],
                [],
                [
                    (("M", 1.0, 0), ("Sp", ("RIGHT", 0))),
                    (("M", 1.0, 0), ("Sm", ("RIGHT", 0))),
                ],
                [],
            ],
        },
        "SxMIDDLE": {
            "nb_param": 1,
            "qname_ideal": ["SU2", (2,)],
            "qname_allowed": ["None", "U1", "SU2"],
            "period": -1,
            "submodel": [],
            "ham_expr": [
                [],
                [],
                [
                    (("M", 1.0, 0), ("Sp", ("MIDDLE", 0))),
                    (("M", 1.0, 0), ("Sm", ("MIDDLE", 0))),
                ],
                [],
            ],
        },
        "ionanisotropy": {
            "nb_param": 1,
            "qname_ideal": ["U1", (1,)],
            "qname_allowed": ["None", "U1"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[(("M", +1.0, 0), ("Sz^2", 0))], [], [], []],
        },
        # ### model
        # 'ising' : {'nb_param' : 2, 'qname_ideal' : ['U1', (1,)],'qname_allowed' : ['None','U1'], 'period' : 1,
        #     'submodel' : [('xx',[0]),('hz',[1])],
        #     'ham_expr' : [ [], [], [], [] ] },
        "xxx": {
            "nb_param": 1,
            "qname_ideal": ["SU2", (2,)],
            "qname_allowed": ["None", "U1"],
            "period": 1,
            "submodel": [("xy", [0]), ("zz", [0])],
            "ham_expr": [[], [], [], []],
        },
        "xxz": {
            "nb_param": 2,
            "qname_ideal": ["SU2", (2,)],
            "qname_allowed": ["None", "U1"],
            "period": 1,
            "submodel": [("xy", [0]), ("zz", [1])],
            "ham_expr": [[], [], [], []],
        },
        "xxz-hz": {
            "nb_param": 3,
            "qname_ideal": ["U1", (1,)],
            "qname_allowed": ["None", "U1"],
            "period": 1,
            "submodel": [("xxz", [0, 1]), ("hz", [2])],
            "ham_expr": [[], [], [], []],
        },
        # 'xxz-hzN' : {'nb_param' : 3, 'qname_ideal' : ['None', (1,)],'qname_allowed' : ['None','U1'], 'period' : 1,
        #     'submodel' : [('xxz',[0,1]),('hz',[2])],
        #     'ham_expr' : [ [], [], [], [] ] },
        "xxx-dimer": {
            "nb_param": 2,
            "qname_ideal": ["SU2", (2,)],
            "qname_allowed": ["None", "U1", "SU2"],
            "period": 1,
            "submodel": [("xydimer", [0, 1]), ("zzdimer", [0, 1])],
            "ham_expr": [[], [], [], []],
        },
        "xxx-dimer-hz": {
            "nb_param": 3,
            "qname_ideal": ["U1", (2,)],
            "qname_allowed": ["None", "U1"],
            "period": 1,
            "submodel": [("xydimer", [0, 1]), ("zzdimer", [0, 1]), ("hz", [2])],
            "ham_expr": [[], [], [], []],
        },
        "xxz-SxBord": {
            "nb_param": 3,
            "qname_ideal": ["SU2", (2,)],
            "qname_allowed": ["None", "U1"],
            "period": 1,
            "submodel": [("xy", [0]), ("zz", [1]), ("SxRIGHT", [2]), ("SxLEFT", [2])],
            "ham_expr": [[], [], [], []],
        },
        # ### so spin ONE
        "xxz-Dz-hz": {
            "nb_param": 4,
            "qname_ideal": ["U1", (2,)],
            "qname_allowed": ["None", "U1"],
            "period": 1,
            "submodel": [("xxz", [0, 1]), ("ionanisotropy", [2]), ("hz", [3])],
            "ham_expr": [[], [], [], []],
        },
        "xxx-Dz-hz": {
            "nb_param": 3,
            "qname_ideal": ["U1", (2,)],
            "qname_allowed": ["None", "U1"],
            "period": 1,
            "submodel": [("xxx", [0]), ("ionanisotropy", [1]), ("hz", [2])],
            "ham_expr": [[], [], [], []],
        },
        # ### ld LADDERS
        "ldhxId": {
            "nb_param": 1,
            "qname_ideal": ["None", (1,)],
            "qname_allowed": ["None"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[(("M", -1.0, 0), ("SxId", 0))], [], [], []],
        },
        "ldIdhx": {
            "nb_param": 1,
            "qname_ideal": ["None", (1,)],
            "qname_allowed": ["None"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[(("M", -1.0, 0), ("IdSx", 0))], [], [], []],
        },
        "ldhzId": {
            "nb_param": 1,
            "qname_ideal": ["U1", (1,)],
            "qname_allowed": ["None", "U1"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[(("M", -1.0, 0), ("SzId", 0))], [], [], []],
        },
        "ldIdhz": {
            "nb_param": 1,
            "qname_ideal": ["U1", (1,)],
            "qname_allowed": ["None", "U1"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[(("M", -1.0, 0), ("IdSz", 0))], [], [], []],
        },
        # 'ldhzTR' : {'nb_param' : 1, 'qname_ideal' : ['U1', (1,)],'qname_allowed' : ['None','U1'], 'period' : -1,
        #     'submodel' : [],
        #     'ham_expr' : [ [( 0, ('MR', [-1.] ), ('Sz', 0))], [], [], [] ] },
        "ldxy-rung": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [],
            "ham_expr": [
                [
                    (("M", 1.0 / 2.0, 0), ("SpSm", 0)),
                    (("M", 1.0 / 2.0, 0), ("SmSp", 0)),
                ],
                [],
                [],
                [],
            ],
        },
        "ldxy-leg11": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [],
            "ham_expr": [
                [],
                [
                    (("M", 1.0 / 2.0, 0), ("SpIdoSmId", 0)),
                    (("M", 1.0 / 2.0, 0), ("SmIdoSpId", 0)),
                ],
                [],
                [],
            ],
        },
        "ldxy-leg22": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [],
            "ham_expr": [
                [],
                [
                    (("M", 1.0 / 2.0, 0), ("IdSpoIdSm", 0)),
                    (("M", 1.0 / 2.0, 0), ("IdSmoIdSp", 0)),
                ],
                [],
                [],
            ],
        },
        "ldxy-leg12": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [],
            "ham_expr": [
                [],
                [
                    (("M", 1.0 / 2.0, 0), ("SpIdoIdSm", 0)),
                    (("M", 1.0 / 2.0, 0), ("SmIdoIdSp", 0)),
                ],
                [],
                [],
            ],
        },
        "ldxy-leg21": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [],
            "ham_expr": [
                [],
                [
                    (("M", 1.0 / 2.0, 0), ("IdSpoSmId", 0)),
                    (("M", 1.0 / 2.0, 0), ("IdSmoSpId", 0)),
                ],
                [],
                [],
            ],
        },
        # # 'xyL-2site' : {'nb_param' : 1, 'qname_ideal' : ['SU2', (2,)],'qname_allowed' : ['None','U1','SU2'], 'period' : 2,
        # #     'submodel' : [],
        # #     'ham_expr' : [ [], [], [( 0, ('M', [1./2.]), ('SpSm', 0)),(0, ('M', 1./2.),('SmSp', 0))], []] },
        # 'xyleg11-dimer' : {'nb_param' : 2, 'qname_ideal' : ['SU2', (2,)],'qname_allowed' : ['None','U1','SU2'], 'period' : 2,
        #     'submodel' : [],
        #     'ham_expr' : [ [], [( 0, ('M', [1./2.]), ('SpIdoSmId', 0)),(0, ('M', [1./2.]),('SmIdoSpId', 0)),( 1, ('M', [1./2.]), ('SpIdoSmId', 1)),(1, ('M', [1./2.]),('SmIdoSpId', 1))], [], []] },
        # 'xyleg22-dimer' : {'nb_param' : 2, 'qname_ideal' : ['SU2', (2,)],'qname_allowed' : ['None','U1','SU2'], 'period' : 2,
        #     'submodel' : [],
        #     'ham_expr' : [ [], [( 0, ('M', [1./2.]), ('IdSpoIdSm', 0)),(0, ('M', [1./2.]),('IdSmoIdSp', 0)),( 1, ('M', [1./2.]), ('IdSpoIdSm', 1)),(1, ('M', [1./2.]),('IdSmoIdSp', 1))], [], []] },
        "ldxy-flux-rung": {
            "nb_param": 2,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [],
            "ham_expr": [
                [
                    (("EXP", [1.0 / 2.0, +1.0j], [0, 1]), ("SpSm", 0)),
                    (("EXP", [1.0 / 2.0, -1.0j], [0, 1]), ("SmSp", 0)),
                ],
                [],
                [],
                [],
            ],
        },
        "ldxy-flux-leg11": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [],
            "ham_expr": [
                [],
                [
                    (("EXP", [1.0 / 2.0, +1.0j], [0, 1]), ("SpIdoSmId", 0)),
                    (("EXP", [1.0 / 2.0, -1.0j], [0, 1]), ("SmIdoSpId", 0)),
                ],
                [],
                [],
            ],
        },
        "ldxy-flux-leg22": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [],
            "ham_expr": [
                [],
                [
                    (("EXP", [1.0 / 2.0, -1.0j], [0, 1]), ("IdSpoIdSm", 0)),
                    (("EXP", [1.0 / 2.0, +1.0j], [0, 1]), ("IdSmoIdSp", 0)),
                ],
                [],
                [],
            ],
        },
        "ldxy-flux-border-rung": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": -1,
            "submodel": [],
            "ham_expr": [
                [],
                [],
                [
                    (("EXP", [1.0 / 2.0, +1.0j], [0, 1]), ("SpSm", ("RIGHT", 0))),
                    (("EXP", [1.0 / 2.0, -1.0j], [0, 1]), ("SmSp", ("RIGHT", 0))),
                    (("EXP", [1.0 / 2.0, -1.0j], [0, 1]), ("SpSm", ("LEFT", 0))),
                    (("EXP", [1.0 / 2.0, +1.0j], [0, 1]), ("SmSp", ("LEFT", 0))),
                ],
                [],
            ],
        },
        "ldzz-rung": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[(("M", 1.0, 0), ("SzSz", 0))], [], [], []],
        },
        "ldzz-leg11": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[], [(("M", 1.0, 0), ("SzIdoSzId", 0))], [], []],
        },
        "ldzz-leg22": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[], [(("M", 1.0, 0), ("IdSzoIdSz", 0))], [], []],
        },
        "ldzz-leg12": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[], [(("M", 1.0, 0), ("SzIdoIdSz", 0))], [], []],
        },
        "ldzz-leg21": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [],
            "ham_expr": [[], [(("M", 1.0, 0), ("IdSzoSzId", 0))], [], []],
        },
        # # 'ldzzL2sites' : {'nb_param' : 1, 'qname_ideal' : ['SU2detached', (2,)],'qname_allowed' : ['None','U1comb','SU2detached'], 'period' : 1,
        # #     'submodel' : [],
        # #     'ham_expr' : [ [], [( 0, ('M', [1.]), ('SzSz', 0) )], [], [] ] },
        # 'ldzzIdleg11dimer' : {'nb_param' : 2, 'qname_ideal' : ['SU2detached', (2,)],'qname_allowed' : ['None','U1comb','SU2detached'], 'period' : 2,
        #     'submodel' : [],
        #     'ham_expr' : [ [], [( 0, ('M', [1.]), ('SzIdoSzId', 0) ),( 1, ('M', [1.]), ('SzIdoSzId', 1) )], [], [] ] },
        # 'ldIdzzleg22dimer' : {'nb_param' : 2, 'qname_ideal' : ['SU2detached', (2,)],'qname_allowed' : ['None','U1comb','SU2detached'], 'period' : 2,
        #     'submodel' : [],
        #     'ham_expr' : [ [], [( 0, ('M', [1.]), ('IdSzoIdSz', 0) ),( 1, ('M', [1.]), ('IdSzoIdSz', 1) )], [], [] ] },
        "ldxxz-rung": {
            "nb_param": 2,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "SU2detached", "U1comb"],
            "period": 1,
            "submodel": [("ldxy-rung", [0]), ("ldzz-rung", [1])],
            "ham_expr": [[], [], [], []],
        },
        "ldxxz-legs": {
            "nb_param": 2,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "SU2detached", "U1comb"],
            "period": 1,
            "submodel": [
                ("ldxy-leg11", [0]),
                ("ldxy-leg22", [0]),
                ("ldzz-leg11", [1]),
                ("ldzz-leg22", [1]),
            ],
            "ham_expr": [[], [], [], []],
        },
        # model !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
        "ldsnake0": {
            "nb_param": 2,
            "qname_ideal": ["U1comb", (1,)],
            "qname_allowed": ["None", "U1comb"],
            "period": 1,
            "submodel": [
                ("ldxy-rung", [0]),
                ("ldzz-rung", [0]),
                ("ldxy-leg12", [1]),
                ("ldzz-leg12", [1]),
            ],
            "ham_expr": [[], [], [], []],
        },
        "ldsnake1": {
            "nb_param": 2,
            "qname_ideal": ["U1comb", (1,)],
            "qname_allowed": ["None", "U1comb"],
            "period": 1,
            "submodel": [
                ("ldxy-rung", [0]),
                ("ldzz-rung", [0]),
                ("ldxy-leg21", [1]),
                ("ldzz-leg21", [1]),
            ],
            "ham_expr": [[], [], [], []],
        },
        # 'ldsnake0-dimer-hz' : {'nb_param' : 2, 'qname_ideal' : ['U1comb', (1,)],'qname_allowed' : ['None','U1comb'], 'period' : 1,
        #     'submodel' : [('ldxy-rung',[0]),('ldzz-rung',[0]),('ldhzId',[2]),('ldIdhz',[2])],
        #     'ham_expr' : [ [], [ ( 1, ('M', [1./2.]), ('SpIdoIdSm', 0)),(1, ('M', [1./2.]),('SmIdoIdSp', 0)),(1, ('M', [1.]),('SzIdoIdSz', 0)) ], [], [] ] },
        # 'ldsnake1-dimer-hz' : {'nb_param' : 2, 'qname_ideal' : ['U1comb', (2,)],'qname_allowed' : ['None','U1comb'], 'period' : 2,
        #     'submodel' : [('ldxy-rung',[0]),('ldzz-rung',[0]),('ldhzId',[2]),('ldIdhz',[2])],
        #     'ham_expr' : [ [], [ ( 1, ('M', [1./2.]), ('IdSpoIdSm', 0)),(1, ('M', [1./2.]),('IdSmoIdSp', 0)),(1, ('M', [1.]),('IdSzoIdSz', 0)),
        #                          ( 1, ('M', [1./2.]), ('SpIdoSmId', 1)),(1, ('M', [1./2.]),('SmIdoSpId', 1)),(1, ('M', [1.]),('SzIdoSzId', 1)) ], [], [] ] },
        "lr-xxz": {
            "nb_param": 4,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [("ldxxz-rung", [2, 3]), ("ldxxz-legs", [0, 1])],
            "ham_expr": [[], [], [], []],
        },
        "lr-xxz-hz": {
            "nb_param": 5,
            "qname_ideal": ["U1comb", (2,)],
            "qname_allowed": ["None", "U1comb"],
            "period": 1,
            "submodel": [("lr-xxz", [0, 1, 2, 3]), ("ldhzId", [4]), ("ldIdhz", [4])],
            "ham_expr": [[], [], [], []],
        },
        # 'ldxxz-hzN' : {'nb_param' : 3, 'qname_ideal' : ['None', (1,)],'qname_allowed' : ['None','U1comb'], 'period' : 1,
        #     'submodel' : [('ldxxz',[0,1]),('ldhzId',[2]),('ldIdhz',[2])],
        #     'ham_expr' : [ [], [], [], [] ] },
        # ###
        #
        #   /|\    /|\
        #  / | \  / | \
        # /__|  \/__|  \
        #
        "ldcoupled_triangle": {
            "nb_param": 5,
            "qname_ideal": ["U1comb", (1,)],
            "qname_allowed": ["None", "U1comb"],
            "period": 2,
            "submodel": [("ldhzId", [4])],
            "ham_expr": [
                [
                    (("M", 1.0 / 2.0, 0), ("SpSm", 1)),
                    (("M", 1.0 / 2.0, 0), ("SmSp", 1)),
                    (("M", 1.0, 1), ("SzSz", 1)),
                    (("M", -1.0, 4), ("IdSz", 1)),
                ],
                [
                    (("M", 1.0 / 2.0, 0), ("SpIdoSmId", 0)),
                    (("M", 1.0 / 2.0, 0), ("SmIdoSpId", 0)),
                    (("M", 1.0, 1), ("SzIdoSzId", 0)),
                    (("M", 1.0 / 2.0, 0), ("SpIdoIdSm", 0)),
                    (("M", 1.0 / 2.0, 0), ("SmIdoIdSp", 0)),
                    (("M", 1.0, 1), ("SzIdoIdSz", 1)),
                    (("M", 1.0 / 2.0, 2), ("IdSpoSmId", 1)),
                    (("M", 1.0 / 2.0, 2), ("IdSmoSpId", 1)),
                    (("M", 1.0, 3), ("IdSzoSzId", 1)),
                ],
                [],
                [],
            ],
        },
        # 'ldcoupled_triangle_flux' : {'nb_param' : 5, 'qname_ideal' : ['U1comb', (1,)],'qname_allowed' : ['None','U1comb'], 'period' : 2,
        #     'submodel' : [('ldhzId',[4])],
        #     'ham_expr' : [ [( ('M', 1./2., 0), ('SpSm', 1)), ( ('M', 1./2., 0), ('SmSp', 1)), ( ('M', 1., 1), ('SzSz', 1)), ( ('M', -1., 4), ('IdSz', 1)) ], [( ('M', 1./2., 0), ('SpIdoSmId', 0)),( ('M', 1./2., 0),('SmIdoSpId', 0)),( ('M', 1., 1),('SzIdoSzId', 0)), ( ('M', 1./2., 0), ('SpIdoIdSm', 0)), ( ('M', 1./2., 0),('SmIdoIdSp', 0)),( ('M', 1., 1),('SzIdoIdSz', 1)), ( ('M', 1./2., 2), ('IdSpoSmId', 1)),(('M', 1./2., 2),('IdSmoSpId', 1)),( ('M', 1., 3),('IdSzoSzId', 1)) ], [], [] ] },
        # 'ldcoupled_triangle_neel_flux' : {'nb_param' : 5, 'qname_ideal' : ['U1comb', (1,)],'qname_allowed' : ['None','U1comb'], 'period' : 4,
        #     'submodel' : [('ldhzId',[4])],
        #     'ham_expr' : [ [( ('M', 1./2., 0), ('SpSm', 1)), ( ('M', 1./2., 0), ('SmSp', 1)), ( ('M', 1., 1), ('SzSz', 1)), ( ('M', -1., 4), ('IdSz', 1)) ], [( ('M', 1./2., 0), ('SpIdoSmId', 0)),( ('M', 1./2., 0),('SmIdoSpId', 0)),( ('M', 1., 1),('SzIdoSzId', 0)), ( ('M', 1./2., 0), ('SpIdoIdSm', 0)), ( ('M', 1./2., 0),('SmIdoIdSp', 0)),( ('M', 1., 1),('SzIdoIdSz', 1)), ( ('M', 1./2., 2), ('IdSpoSmId', 1)),(('M', 1./2., 2),('IdSmoSpId', 1)),( ('M', 1., 3),('IdSzoSzId', 1)) ], [], [] ] },
        # 'ldcoupled_square' : {'nb_param' : 3, 'qname_ideal' : ['SU2', (2,)],'qname_allowed' : ['None','U1'], 'period' : 2,
        #     'submodel' : [('xyrung',[0]),('zzrung',[0]),('hzId',[2]),('Idhz',[2])],
        #     'ham_expr' : [ [ ], [( 0, ('M', [1./2.]), ('SpIdoSmId', 0)),(0, ('M', [1./2.]),('SmIdoSpId', 0)),(0, ('M', [1./2.]),('SzIdoSzId', 0)), ( 0, ('M', [1./2.]), ('IdSpoIdSm', 0)),(0, ('M', [1./2.]),('IdSmoIdSp', 0)),(0, ('M', [1./2.]),('IdSzoIdSz', 0)), ( 1, ('M', [1./2.]), ('SpIdoSmId', 1)),(1, ('M', [1./2.]),('SmIdoSpId', 1)),(1, ('M', [1./2.]),('SzIdoSzId', 1)), ( 1, ('M', [1./2.]), ('IdSpoIdSm', 1)),(1, ('M', [1./2.]),('IdSmoIdSp', 1)),(1, ('M', [1./2.]),('IdSzoIdSz', 1)) ], [], [] ] },
        "ldspincurrent": {
            "nb_param": 1,
            "qname_ideal": ["SU2detached", (2,)],
            "qname_allowed": ["None", "U1comb", "SU2detached"],
            "period": 1,
            "submodel": [
                ("ldxy-flux-leg11", [0]),
                ("ldxy-flux-leg22", [0]),
                ("ldxy-flux-border-rung", [0]),
            ],
            "ham_expr": [[], [], [], []],
        },
        # 'ldsh-xxx-hz-dimJ1J2' :
        #     {'nb_param' : 3, 'qname' : ['ldsh-U1comb', (2,)], 'period' : 2,
        #      'ham_expr' : [ [(1, 1/2.,'ldsh-SmIdIdSp'),(1, 1/2.,'ldsh-SpIdIdSm'),(1, 1/2.,'ldsh-IdSmSpId'),(1, 1/2.,'ldsh-IdSpSmId'),(1, 1.,'ldsh-SzIdIdSz'),(1, 1.,'ldsh-IdSzSzId')],
        #                     [(0, 1/2.,'ldsh-SpSm'),(0, 1/2.,'ldsh-SmSp'),(0, 1.,'ldsh-SzSz'),(2, -1.,'ldsh-SzId'),(2, -1.,'ldsh-IdSz')],
        #                     [],
        #                     [] ],
        #      'ham_expr0' : [ [(0, 1/2.,'ldsh-SmIdSpId'),(0, 1/2.,'ldsh-SpIdSmId'),(0, 1.,'ldsh-SzIdSzId')],
        #                     [],
        #                     [],
        #                     [] ],
        #      'ham_expr1' : [ [(0, 1/2.,'ldsh-IdSmIdSp'),(0, 1/2.,'ldsh-IdSpIdSm'),(0, 1.,'ldsh-IdSzIdSz')],
        #                     [],
        #                     [],
        #                     [] ]
        #  },
        # 'ldsh-xxz-hz-dimJ1J2' :
        #     {'nb_param' : 5, 'qname' : ['ldsh-U1comb', (2,)], 'period' : 2,
        #      'ham_expr' : [ [(2, 1/2.,'ldsh-SmIdIdSp'),(2, 1/2.,'ldsh-SpIdIdSm'),(2, 1/2.,'ldsh-IdSmSpId'),(2, 1/2.,'ldsh-IdSpSmId'),(3, 1.,'ldsh-SzIdIdSz'),(3, 1.,'ldsh-IdSzSzId')],
        #                     [(0, 1/2.,'ldsh-SpSm'),(0, 1/2.,'ldsh-SmSp'),(1, 1.,'ldsh-SzSz'),(4, -1.,'ldsh-SzId'),(4, -1.,'ldsh-IdSz')],
        #                     [],
        #                     [] ],
        #      'ham_expr0' : [ [(0, 1/2.,'ldsh-SmIdSpId'),(0, 1/2.,'ldsh-SpIdSmId'),(1, 1.,'ldsh-SzIdSzId')],
        #                     [],
        #                     [],
        #                     [] ],
        #      'ham_expr1' : [ [(0, 1/2.,'ldsh-IdSmIdSp'),(0, 1/2.,'ldsh-IdSpIdSm'),(1, 1.,'ldsh-IdSzIdSz')],
        #                     [],
        #                     [],
        #                     [] ]
        # }
    }
